### ISSUE TITLE
sfdx-cli@7.209.6: sfdx-cli is deprecated

### ISSUE THREAD

**Issue by lramosmtx** [hardisgroupcom/vscode-sfdx-hardis#107]
When I upgrade all the plugin, I get the warning message
sfdx-cli@7.209.6: sfdx-cli is deprecated, and no updates are planned.  Use @salesforce/cli instead.  See https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

Could the plugin do the action?
npm uninstall sfdx-cli --global
npm install @salesforce/cli --global

Thanks in advance

**Comment by nvuillam** [comment]
@lramosmtx you're right :)
PR ongoing, before merging I'll make more tests to make sure it works for all configs, then make a video explanation to avoid users to be too scared :)
