### ISSUE TITLE
Error deleting obsolete flows

### ISSUE THREAD

**Issue by spw-dhurran** [hardisgroupcom/vscode-sfdx-hardis#129]
? 🦙 Do you confirm you want to delete these 46 flow versions ? ✅ Yes
[sfdx-hardis] Error deleting Flow records:[object Object]
SfdxError: Error deleting Flow records:[object Object]
    at handleCallback (/Users/firstname.lastname/.local/share/sf/node_modules/sfdx-hardis/lib/common/utils/apiUtils.js:122:23)
    at /Users/firstname.lastname/.local/share/sf/node_modules/sfdx-hardis/node_modules/jsforce/lib/promise.js:76:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
ERROR running hardis:org:purge:flow:  Cannot read properties of undefined (reading '_toRecordResult')
[sfdx-hardis] hardis:org:purge:flow execution time 0:00:44.509

<img width="338" alt="image" src="https://github.com/user-attachments/assets/d560667c-2ef1-4231-bfe4-eb2b36fe1e80">

Node Version v20.8.0
git version 2.39.3 (Apple Git-146)

**Comment by nvuillam** [comment]
Moved to https://github.com/hardisgroupcom/sfdx-hardis/issues/662
