### ISSUE TITLE
command Failed: node --version /bin/sh: 1: node not found, UriError: Scheme contains illegal characters errors on refresh and load extension

### ISSUE THREAD

**Issue by apsoftwaredev** [hardisgroupcom/vscode-sfdx-hardis#41]
![image](https://user-images.githubusercontent.com/1483796/130333837-38030c77-a9fc-4889-ada6-951ad24e2917.png)

Output if I run
```
> sfdx --version
sfdx-cli/7.114.0 linux-x64 node-v14.17.5

>which node
/home/node/.nvm/versions/node/v14.17.5/bin/node

```
~ is /root
in docker container
![image](https://user-images.githubusercontent.com/1483796/130334111-ed4f9d0f-5889-4551-9bc6-bb9221e91a24.png)

![image](https://user-images.githubusercontent.com/1483796/130334323-53ad2ad0-68fe-4287-a7b7-790e0aba3dc8.png)

Looks like I need to set the node location somewhere or an environmental variable for the extension.

Thanks, It looks like a great extension.

**Comment by apsoftwaredev** [comment]
I use Windows Terminal in VS Code,  with zsh on Ubuntu in a Docker Container

Windows Terminal
Version: 1.9.1942.0

I added this to the ~/.zshrc

export NVMHOME="/home/node"
export NVM_DIR="home/node/.nvm"
export NODE_PATH="/home/node/.nvm/versions/node/v14.17.5/bin/node"
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${NVMHOME}/.nvm" || printf %s "${XDG_CONF$
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvmexport NVM_DIR="/home/node/.nvm"

**Comment by nvuillam** [comment]
I think the code is lost because of nvm use, I have a provide a fix

What is the output when you try `node --version` in your command line ?

**Comment by nvuillam** [comment]
I released v1.60.1 with an improved way to check for node.js existence

@apsoftwaredev  As my config is far from yours, i've not been able to test your case, please can you check and confirm (or not) that it works better ?

Thanks !

**Comment by apsoftwaredev** [comment]
Thank you  for your fast reply.  

I installed the update and checked to make sure that the $NODE_PATH was set.  It gave some different error messages but did not seem to find it. 

Should I set the env variable somewhere in vscode?

![image](https://user-images.githubusercontent.com/1483796/130338170-3f58bc3d-d22c-48ab-bd26-893d415cf464.png)

**Comment by apsoftwaredev** [comment]
![image](https://user-images.githubusercontent.com/1483796/130338199-432a4ff5-7f68-4135-b099-4f776f7ebc50.png)

**Comment by apsoftwaredev** [comment]
Could I put something like this in my project launch.json?
I don't know the type.

Thanks.

 {
        "name": "SFDX Hardis",
       "type":"node",
       "request": "launch",
        "env": {
          "NODE_ENV": "development",
          "NODE_PATH": "/home/node/.nvm/versions/node/v14.17.5/bin/node",
        },

**Comment by apsoftwaredev** [comment]
Here is what I did to set up the sfdx environment. 

You can test it in the salesforce docker
docker pull salesforce/salesforcedx:latest-rc-full
docker run -it salesforce/salesforcedx:latest-rc-full

then uninstalled the nodejs they have to use nvm
I believe I ran this:

```
rm -rf /usr/local/bin/npm /usr/local/lib/dtrace/node.d ~/.npm ~/.node-gyp /opt/local/bin/node opt/local/include/node /opt/local/lib/node_modules
```
but it might not have worked.
```
rm -rf /usr/local/lib/node*
rm -rf /usr/local/include/node* 
rm -rf /usr/local/bin/node*  
```
Whatever the best way to remove nodejs....
then:
```
HOME=/home/node
USER=node
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
HOME=/root/   
nvm --version 
nvm install 14.17.5
npm install --global sfdx-cli@latest-rc  
```

then I added this to my .zshrc (after setting up zsh)

```
export NVMHOME="/home/node"
export NVM_DIR="/home/node/.nvm"
export NODE_PATH="/home/node/.nvm/versions/node/v14.17.5/bin/node"
export NODE_ENV="Development"
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${NVMHOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvmexport NVM_DIR="/home/node/.nvm"

```
If you try to install the nvm in the root it gives permission errors so you have to make a /home/node to install the global packages




 PATH="/home/node/.npm-global/bin:${PATH}" 
NPM_CONFIG_PREFIX="/home/node/.npm-global"
mkdir -p "${NPM_CONFIG_PREFIX}/lib"  
npm --global config set user "${USER}" \  
npm --global --quiet --no-progress install \    
&& npm cache clean --force
  
   
```

I added this to the path:
```
/home/node/.nvm/versions/node/v14.17.5/bin
```

**Comment by apsoftwaredev** [comment]
Maybe it would be good to have a settings variable like eslint has for node path.
like:
```
"eslint.nodeEnv": "development",
    "eslint.nodePath": "/home/node/.nvm/versions/node/v14.17.5/bin/node",
```

**Comment by ethon-wang** [comment]
Win10 users encountered a similar problem. I need to use nvm to switch the node environment. Currently, I solve the problem of hardis reporting a low node version by setting up the environment variable NODE_PATH to point to the new node version (the local default is a lower version). Am I doing the right thing?
