### ISSUE TITLE
sfdx hardis:project:clean:references leads to different formatting of whole profiles

### ISSUE THREAD

**Issue by busybox0** [hardisgroupcom/vscode-sfdx-hardis#51]
great plugin, though when I run **sfdx hardis:project:clean:references**  it shrinks profiles indentation from 4 spaces as a tab stop to 2 spaces. 
The standard formatting in Salesforce is 4 spaces. That is how you are getting profiles on retrieve.
The indentation change makes git thinking that whole profile files being changed (with little subset of lines deleted). 
This, in turn, leads to inconvenience if subsequent pulls/retrieves are needed for profiles.
Is there a quick way to influence/fix the indentation ?

![Screenshot 2021-12-02 114056](https://user-images.githubusercontent.com/6568234/144396809-2202e4ef-8fac-4614-b65a-5df1a2f1ff52.png)

**Comment by nvuillam** [comment]
Good catch, there's probably something to do about it :)

I'll try to publish a fix ASAP :)

**Comment by nvuillam** [comment]
@busybox0 It should be ok now :) ( I made a quick test but I prefer if you confirm that it's ok on your side too !)

Note: you need to upgrade plugins **sfdx-hardis** (2.61.0) and **sfdx-essentials** (2.11.0)

**Comment by busybox0** [comment]
Thanks for the quick turnaround, though it seems didn't help. Both profiles and permission sets decreased indentation as on picture above.

$ sfdx --version
sfdx-cli/7.129.0 wsl-x64 node-v14.17.6

$ sfdx plugins
sfdmu 4.10.3
sfdx-essentials 2.11.0
sfdx-git-delta 4.11.0
sfdx-hardis 2.61.0
sfdx-profiles-splitter 0.1.0
sfdx-wry-plugin 0.0.11
sfpowerkit 3.3.4
shane-sfdx-plugins 4.43.0
├─ @mshanemc/sfdx-sosl 1.1.0
└─ @mshanemc/plugin-streaming 1.1.7
texei-sfdx-plugin 1.12.0


$ sfdx hardis:project:clean:references -t all --config tmp/destructiveChanges/destructiveChanges.xml
[sfdx-hardis][command] git config --list --show-origin --null
[sfdx-hardis] Apply cleaning of references to tmp/destructiveChanges/destructiveChanges.xml...
✔ [sfdx-hardis][command] sfdx essentials:metadata:filter-xml-content -c /tmp/sfdx-hardis-x49j18/clean_destructiveChanges.xml.json --inputfolder ./force-app/main/default --outputfolder ./force-app/main/default --noinsight
[sfdx-hardis] Cleaning package.xml files...
[sfdx-hardis] Removing obsolete files...
[sfdx-hardis] Cleaning complete
[sfdx-hardis] hardis:project:clean:references execution time 0:00:52.946

**Comment by nvuillam** [comment]
My test was probably not advanced enough, i'll have a look and provide you feedback within the next few days :)

**Comment by busybox0** [comment]
thanks Nicolas, 
also, it seems to change the 1st line of xml, 
before: ```<?xml version="1.0" encoding="UTF-8" ?>```
after :   ```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>```

**Comment by nvuillam** [comment]
@busybox0 now it should all be ok :) ( I tested on my own project files ^^ )

- 4 spaces indentation
- no more `standalone="true"`

Please can you confirm that it's ok on your side too ? :)

Requires:
- sfdx-essentials v2.12.0
- sfdx-hardis v2.62.0

Just accept plugins auto-update message at VsCode SFDX Hardis startup, or manually run the following commands ;)

```shell
sfdx plugins:install sfdx-essentials
sfdx plugins:install sfdx-hardis
```

**Comment by nvuillam** [comment]
@busybox0 can I close the issue ?
My tests are all ok on my side :)

**Comment by nvuillam** [comment]
Works on my side :)
