### ISSUE TITLE
Feature: Add new Commands

### ISSUE THREAD

**Issue by KushalB** [hardisgroupcom/vscode-sfdx-hardis#58]
There should be a way where we can add new commands. Ideally a new button to add new command from the menu which would ask the user to either create or update a custom command file where new commands can be added directly into the file. The file should be a json. Once a new command object is added or modified, it should refresh the custom command list on the menu as well. 

This feature will give immense benefit to a developer.

**Comment by nvuillam** [comment]
hi @KushalB , thanks for your interest in sfdx-hardis :)

The philosophy of the plugin is to provide shortcuts to the commands that we consider useful for a Salesforce project.
Do you have examples of additional commands that you would need ? They could be easily added in the plugin sources

If your need is really to be able to add as many commands as you like (and not just a few ones), please explain the use case and we could see about:
- Implementing the capability to define custom list of commands in a json / js file
- Manage publication of such command list extensions (maybe as VsCode extensions ?)

**Comment by KushalB** [comment]
Hi @nvuillam - thanks for the quick response. 

The idea originated while I was deploying few classes to a production org by providing a specified test class names. I felt if there was a way to store the command in some way or the other and make it's invocation clickable, that would be good. 

Apart from this one - there's static code analysis with PMD that I use quite a lot to generate a csv report of rule violations. There can be many more examples specific to a certain developers' need. 

I hope I was able to give you some context. 

If you consider this to be a legitimate use case and proceed with the enhancement request, I would love to contribute in this project as well.

**Comment by nvuillam** [comment]
@KushalB > this is done and released :)

https://github.com/hardisgroupcom/vscode-sfdx-hardis#custom-commands

Please let me know if it works well for your use cases :)

**Comment by nvuillam** [comment]
I'm glad if it helped you :)

In order to make the capability cross-project, I even thought about allowing to add a VsCode setting allowing to force the path to a .sfdx-hardis.yml file containing custom commands, which could be:
- defined with absolute path to a location on the hard drive
- defined online ( https:// .... )

Would it help your cases ?

**Comment by KushalB** [comment]
I feel the online one would be a great way to transport/share custom commands within teams. Also there's a prospect of having a custom command plug and play library that can be referenced through this VS Code Extension settings.

**Comment by nvuillam** [comment]
I'll do that someday ,thanks for your feedback :)

**Comment by nvuillam** [comment]
@KushalB now you can define a remote .sfdx-hardis.yml containing `customCommands` and `customCommandsPosition` :)

-> https://github.com/hardisgroupcom/vscode-sfdx-hardis#custom-commands

![image](https://user-images.githubusercontent.com/17500430/162630906-55685dbb-3a0f-44d3-afa4-d7e4c5ae0923.png)
