### ISSUE TITLE
"Disable Vs Code Colors" not properly disabled?

### ISSUE THREAD

**Issue by marcbourlon** [hardisgroupcom/vscode-sfdx-hardis#94]
Hi there.
I like using the VS Code Peacock extension to differentiate between several projects, thanks to colouring my VS Code UI elements.
Of course, Hardis' colour option conflicts with it Peacock's action, the main reason being an issue with contrast (the icon color remains black on dark red)
So, I disabled Hardis' Vs Code Colors by ticking the checkbox.
But now, it's worse 😂, as it's black text on black background.
![Screenshot 2023-05-19 at 12 09 36](https://github.com/hardisgroupcom/vscode-sfdx-hardis/assets/1508973/181e23b6-6d74-4b99-91d6-d6314c1ca39e)
Could this be fixed, please?

**Comment by nvuillam** [comment]
@marcbourlon please can you share the content of your .vscode/settings file ?

Sfdx hardis just adds properties there, nowhere else ^^

**Comment by nvuillam** [comment]
@marcbourlon any news ? :)
